services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    image: "postgres-test"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - test-db:/data/test-db
    ports:
      - "8080:5432"
    restart: unless-stopped
volumes:
    test-db:
      external: true  # Внешний том
